name: CI - AuthService + FileService

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

# Set default permissions for the workflow
permissions:
  contents: read

jobs:
  authService:
    name: AuthService - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (authService)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/authService/requirements.txt

      - name: Run tests (authService)
        run: |
          pytest backend/authService/tests -v

  fileService:
    name: FileService - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (fileService)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/fileService/requirements.txt

      - name: Run tests (fileService)
        run: |
          pytest backend/fileService/tests -v
